### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by ZestyChicken** [ceyounger/docker-maraschino-plex#1]
Nice docker. I got it working on an unraid installation though I had to add a few arguments:
/config to put configuration files in a separate location outside the docker. Using the "HOME" option doesn't seem to work by itself though I point it to the same locations config. I'm not really sure what "HOME" does. 
/data to allow access to my mounted drives (e.g. /mnt/) from within the docker for the diskspace app within Maraschino
Host Port 1 so that I can define the port the app runs on.

Is there any way to add to the docker the cherry icon that they use here: https://github.com/linuxserver/docker-maraschino

Here is the direct link to the image:
https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/maraschino.png

The Linuxsever version displays the icon when you install it.

**Comment by ceyounger** [comment]
Good idea--most of the containers I use on my Synology have a similar format.  When I get a chance I'll incorporate the /config and /data changes.  Looks like you solved the icon issue, I'll dump an icon in there too.

**Comment by ceyounger** [comment]
Added the favicon and added /config and /data to volumes.  Let me know if anything else breaks
